/*
 * --------------------------------------------------------------------------------------
 * <copyright company="Aspose" file="ExecuteMailMergeRequest.java">
 *   Copyright (c) 2019 Aspose.Words for Cloud
 * </copyright>
 * <summary>
 *   Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 * 
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 * 
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 * </summary>
 * --------------------------------------------------------------------------------------
 */
package com.aspose.words.cloud.model.requests;
import com.aspose.words.cloud.model.*;
import java.io.File;

/*
 * Request model for executeMailMerge operation.
 */
public class ExecuteMailMergeRequest {
    /*
     * The document name.
     */
    private  Name;

    /*
     * Mail merge data
     */
    private  Data;

    /*
     * Original document folder.
     */
    private  Folder;

    /*
     * Original document storage.
     */
    private  Storage;

    /*
     * Encoding that will be used to load an HTML (or TXT) document if the encoding is not specified in HTML.
     */
    private  LoadEncoding;

    /*
     * Password for opening an encrypted document.
     */
    private  Password;

    /*
     * With regions flag.
     */
    private  WithRegions;

    /*
     * Mail merge data.
     */
    private  MailMergeDataFile;

    /*
     * Clean up options.
     */
    private  Cleanup;

    /*
     * Gets or sets a value indicating whether paragraph with TableStart or             TableEnd field should be fully included into mail merge region or particular range between TableStart and TableEnd fields.             The default value is true.
     */
    private  UseWholeParagraphAsRegion;

    /*
     * Result name of the document after the operation. If this parameter is omitted then result of the operation will be saved with autogenerated name.
     */
    private  DestFileName;
    
    /*
     * Initializes a new instance of the executeMailMergeRequest class.
     *  
     * @param  name The document name.
     * @param  data Mail merge data
     * @param  folder Original document folder.
     * @param  storage Original document storage.
     * @param  loadEncoding Encoding that will be used to load an HTML (or TXT) document if the encoding is not specified in HTML.
     * @param  password Password for opening an encrypted document.
     * @param  withRegions With regions flag.
     * @param  mailMergeDataFile Mail merge data.
     * @param  cleanup Clean up options.
     * @param  useWholeParagraphAsRegion Gets or sets a value indicating whether paragraph with TableStart or             TableEnd field should be fully included into mail merge region or particular range between TableStart and TableEnd fields.             The default value is true.
     * @param  destFileName Result name of the document after the operation. If this parameter is omitted then result of the operation will be saved with autogenerated name.
     */
    public ExecuteMailMergeRequest( name,   data,   folder,   storage,   loadEncoding,   password,   withRegions,   mailMergeDataFile,   cleanup,   useWholeParagraphAsRegion,   destFileName) {
        Name = name;
        Data = data;
        Folder = folder;
        Storage = storage;
        LoadEncoding = loadEncoding;
        Password = password;
        WithRegions = withRegions;
        MailMergeDataFile = mailMergeDataFile;
        Cleanup = cleanup;
        UseWholeParagraphAsRegion = useWholeParagraphAsRegion;
        DestFileName = destFileName;
    }

    /*
     *  Gets The document name.
     */
    public  getName() {
        return Name;
    }

    /*
     * Sets The document name.
     */
    public void setName( value) {
        Name = value;
    }

    /*
     *  Gets Mail merge data
     */
    public  getData() {
        return Data;
    }

    /*
     * Sets Mail merge data
     */
    public void setData( value) {
        Data = value;
    }

    /*
     *  Gets Original document folder.
     */
    public  getFolder() {
        return Folder;
    }

    /*
     * Sets Original document folder.
     */
    public void setFolder( value) {
        Folder = value;
    }

    /*
     *  Gets Original document storage.
     */
    public  getStorage() {
        return Storage;
    }

    /*
     * Sets Original document storage.
     */
    public void setStorage( value) {
        Storage = value;
    }

    /*
     *  Gets Encoding that will be used to load an HTML (or TXT) document if the encoding is not specified in HTML.
     */
    public  getLoadEncoding() {
        return LoadEncoding;
    }

    /*
     * Sets Encoding that will be used to load an HTML (or TXT) document if the encoding is not specified in HTML.
     */
    public void setLoadEncoding( value) {
        LoadEncoding = value;
    }

    /*
     *  Gets Password for opening an encrypted document.
     */
    public  getPassword() {
        return Password;
    }

    /*
     * Sets Password for opening an encrypted document.
     */
    public void setPassword( value) {
        Password = value;
    }

    /*
     *  Gets With regions flag.
     */
    public  getWithRegions() {
        return WithRegions;
    }

    /*
     * Sets With regions flag.
     */
    public void setWithRegions( value) {
        WithRegions = value;
    }

    /*
     *  Gets Mail merge data.
     */
    public  getMailMergeDataFile() {
        return MailMergeDataFile;
    }

    /*
     * Sets Mail merge data.
     */
    public void setMailMergeDataFile( value) {
        MailMergeDataFile = value;
    }

    /*
     *  Gets Clean up options.
     */
    public  getCleanup() {
        return Cleanup;
    }

    /*
     * Sets Clean up options.
     */
    public void setCleanup( value) {
        Cleanup = value;
    }

    /*
     *  Gets Gets or sets a value indicating whether paragraph with TableStart or             TableEnd field should be fully included into mail merge region or particular range between TableStart and TableEnd fields.             The default value is true.
     */
    public  getUseWholeParagraphAsRegion() {
        return UseWholeParagraphAsRegion;
    }

    /*
     * Sets Gets or sets a value indicating whether paragraph with TableStart or             TableEnd field should be fully included into mail merge region or particular range between TableStart and TableEnd fields.             The default value is true.
     */
    public void setUseWholeParagraphAsRegion( value) {
        UseWholeParagraphAsRegion = value;
    }

    /*
     *  Gets Result name of the document after the operation. If this parameter is omitted then result of the operation will be saved with autogenerated name.
     */
    public  getDestFileName() {
        return DestFileName;
    }

    /*
     * Sets Result name of the document after the operation. If this parameter is omitted then result of the operation will be saved with autogenerated name.
     */
    public void setDestFileName( value) {
        DestFileName = value;
    }
}
